---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: metrics
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: metrics-server
      version: 5.8.6
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
